// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/zackartz/ttd/ent/schema"
	"github.com/zackartz/ttd/ent/timestamp"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	timestampFields := schema.Timestamp{}.Fields()
	_ = timestampFields
	// timestampDescStartTime is the schema descriptor for start_time field.
	timestampDescStartTime := timestampFields[1].Descriptor()
	// timestamp.DefaultStartTime holds the default value on creation for the start_time field.
	timestamp.DefaultStartTime = timestampDescStartTime.Default.(func() time.Time)
	// timestampDescActive is the schema descriptor for active field.
	timestampDescActive := timestampFields[3].Descriptor()
	// timestamp.DefaultActive holds the default value on creation for the active field.
	timestamp.DefaultActive = timestampDescActive.Default.(bool)
	// timestampDescID is the schema descriptor for id field.
	timestampDescID := timestampFields[0].Descriptor()
	// timestamp.DefaultID holds the default value on creation for the id field.
	timestamp.DefaultID = timestampDescID.Default.(func() uuid.UUID)
}
