// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TimestampsColumns holds the columns for the "timestamps" table.
	TimestampsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "start_time", Type: field.TypeTime},
		{Name: "end_time", Type: field.TypeTime},
		{Name: "active", Type: field.TypeBool, Default: true},
		{Name: "comment", Type: field.TypeString, Nullable: true},
		{Name: "category", Type: field.TypeString},
		{Name: "project", Type: field.TypeString, Nullable: true},
	}
	// TimestampsTable holds the schema information for the "timestamps" table.
	TimestampsTable = &schema.Table{
		Name:        "timestamps",
		Columns:     TimestampsColumns,
		PrimaryKey:  []*schema.Column{TimestampsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TimestampsTable,
	}
)

func init() {
}
