// Code generated by entc, DO NOT EDIT.

package timestamp

import (
	"time"

	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the timestamp type in the database.
	Label = "timestamp"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStartTime holds the string denoting the start_time field in the database.
	FieldStartTime = "start_time"
	// FieldEndTime holds the string denoting the end_time field in the database.
	FieldEndTime = "end_time"
	// FieldActive holds the string denoting the active field in the database.
	FieldActive = "active"
	// FieldComment holds the string denoting the comment field in the database.
	FieldComment = "comment"
	// FieldCategory holds the string denoting the category field in the database.
	FieldCategory = "category"
	// FieldProject holds the string denoting the project field in the database.
	FieldProject = "project"
	// Table holds the table name of the timestamp in the database.
	Table = "timestamps"
)

// Columns holds all SQL columns for timestamp fields.
var Columns = []string{
	FieldID,
	FieldStartTime,
	FieldEndTime,
	FieldActive,
	FieldComment,
	FieldCategory,
	FieldProject,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStartTime holds the default value on creation for the "start_time" field.
	DefaultStartTime func() time.Time
	// DefaultActive holds the default value on creation for the "active" field.
	DefaultActive bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
